//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillSync.Pages.admin {
    
    public partial class ManageUsers {
        
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Button btnToggleAddForm;
        protected global::System.Web.UI.WebControls.Panel pnlAddFreelancer;
        protected global::System.Web.UI.WebControls.TextBox txtFreeName;
        protected global::System.Web.UI.WebControls.TextBox txtFreeEmail;
        protected global::System.Web.UI.WebControls.TextBox txtFreePassword;
        protected global::System.Web.UI.WebControls.TextBox txtFreeLocation;
        protected global::System.Web.UI.WebControls.Button btnCancelAddFreelancer;
        protected global::System.Web.UI.WebControls.Button btnAddFreelancerSubmit;

        protected global::System.Web.UI.WebControls.Panel pnlEditUser;
        protected global::System.Web.UI.WebControls.TextBox txtEditUserId;
        protected global::System.Web.UI.WebControls.TextBox txtEditName;
        protected global::System.Web.UI.WebControls.TextBox txtEditEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEditLocation;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditStatus;
        protected global::System.Web.UI.WebControls.Button btnSaveUserEdit;
        protected global::System.Web.UI.WebControls.Button btnCancelUserEdit;

        protected global::System.Web.UI.WebControls.Repeater rptUsers;
    }
}

