//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillSync.Pages.admin {
    
    public partial class ManageServices {
        
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Button btnToggleAddService;
        protected global::System.Web.UI.WebControls.Panel pnlAddService;
        protected global::System.Web.UI.WebControls.DropDownList ddlAddServiceFreelancer;
        protected global::System.Web.UI.WebControls.DropDownList ddlAddServiceCategory;
        protected global::System.Web.UI.WebControls.TextBox txtAddServiceTitle;
        protected global::System.Web.UI.WebControls.TextBox txtAddServiceDesc;
        protected global::System.Web.UI.WebControls.TextBox txtAddServicePrice;
        protected global::System.Web.UI.WebControls.TextBox txtAddServiceDays;
        protected global::System.Web.UI.WebControls.TextBox txtAddServiceExp;
        protected global::System.Web.UI.WebControls.Button btnCancelAddService;
        protected global::System.Web.UI.WebControls.Button btnAddServiceSubmit;

        protected global::System.Web.UI.WebControls.Panel pnlEditService;
        protected global::System.Web.UI.WebControls.TextBox txtEditServiceId;
        protected global::System.Web.UI.WebControls.TextBox txtEditServiceTitle;
        protected global::System.Web.UI.WebControls.TextBox txtEditServicePrice;
        protected global::System.Web.UI.WebControls.TextBox txtEditServiceDays;
        protected global::System.Web.UI.WebControls.TextBox txtEditServiceExp;
        protected global::System.Web.UI.WebControls.TextBox txtEditServiceDesc;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditServiceStatus;
        protected global::System.Web.UI.WebControls.Button btnSaveServiceEdit;
        protected global::System.Web.UI.WebControls.Button btnCancelServiceEdit;

        protected global::System.Web.UI.WebControls.Repeater rptServices;
    }
}

