//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillSync
{


    public partial class Site1
    {

        /// <summary>
        /// head control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// LogoLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink LogoLink;

        /// <summary>
        /// MainLogo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image MainLogo;

        /// <summary>
        /// HomeLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink HomeLink;

        /// <summary>
        /// FindLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink FindLink;

        /// <summary>
        /// MatchLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink MatchLink;

        /// <summary>
        /// CompareLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink CompareLink;

        /// <summary>
        /// LoginLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink LoginLink;

        /// <summary>
        /// LogoutLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink LogoutLink;

        /// <summary>
        /// FooterLogoLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink FooterLogoLink;

        /// <summary>
        /// FooterLogo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image FooterLogo;

        /// <summary>
        /// ContentPlaceHolder1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
    }
}
