//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillSync.Pages.client
{


    public partial class Compare
    {

        /// <summary>
        /// ddlCandidate1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCandidate1;

        /// <summary>
        /// ddlCandidate2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCandidate2;

        /// <summary>
        /// btnCompare control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCompare;

        /// <summary>
        /// imgC1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgC1;

        /// <summary>
        /// imgC2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgC2;

        /// <summary>
        /// imgC3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgC3;

        /// <summary>
        /// hlHire1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlHire1;

        /// <summary>
        /// hlHire2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlHire2;

        /// <summary>
        /// hlHire3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlHire3;
    }
}
