//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillSync.Pages.client
{


    public partial class WebForm1
    {

        /// <summary>
        /// ddlCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        /// <summary>
        /// txtRequirement control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRequirement;

        /// <summary>
        /// btnFind control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnFind;

        /// <summary>
        /// imgFree1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgFree1;

        /// <summary>
        /// hlView1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlView1;

        /// <summary>
        /// imgFree2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgFree2;

        /// <summary>
        /// hlView2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlView2;

        /// <summary>
        /// imgFree3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgFree3;

        /// <summary>
        /// hlView3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlView3;

        /// <summary>
        /// imgFree4 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgFree4;

        /// <summary>
        /// hlView4 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlView4;

        /// <summary>
        /// btnCta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink btnCta;
    }
}
