//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillSync.Pages.client {
    
    
    public partial class Login {
        
        protected global::System.Web.UI.WebControls.Label lblMessage;
        
        protected global::System.Web.UI.WebControls.Panel pnlLogin;
        protected global::System.Web.UI.WebControls.Label lblRole;
        protected global::System.Web.UI.WebControls.DropDownList ddlUserRole;
        protected global::System.Web.UI.WebControls.Label lblEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.Label lblPassword;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.CheckBox chkRemember;
        protected global::System.Web.UI.WebControls.Button btnLogin;

        protected global::System.Web.UI.WebControls.Panel pnlRegister;
        protected global::System.Web.UI.WebControls.TextBox txtRegName;
        protected global::System.Web.UI.WebControls.TextBox txtRegEmail;
        protected global::System.Web.UI.WebControls.TextBox txtRegPassword;
        protected global::System.Web.UI.WebControls.TextBox txtRegLocation;
        protected global::System.Web.UI.WebControls.Button btnRegisterClient;

        protected global::System.Web.UI.WebControls.Button btnToggleMode;
    }
}
