//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillSync.Pages.client
{


    public partial class MatchResults
    {

        /// <summary>
        /// lblSummaryCat control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSummaryCat;

        /// <summary>
        /// lblSummarySkills control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSummarySkills;

        /// <summary>
        /// lblSummaryBudget control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSummaryBudget;

        /// <summary>
        /// lblSummaryExp control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSummaryExp;

        /// <summary>
        /// lblSummaryLoc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSummaryLoc;

        /// <summary>
        /// hlEditReq control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlEditReq;

        /// <summary>
        /// ddlFiltCat control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltCat;

        /// <summary>
        /// ddlFiltBudget control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltBudget;

        /// <summary>
        /// ddlFiltExp control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltExp;

        /// <summary>
        /// ddlFiltMode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltMode;

        /// <summary>
        /// btnApplyFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnApplyFilter;

        /// <summary>
        /// imgM1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgM1;

        /// <summary>
        /// hlComp1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlComp1;

        /// <summary>
        /// imgM2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgM2;

        /// <summary>
        /// hlComp2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlComp2;

        /// <summary>
        /// imgM3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgM3;

        /// <summary>
        /// hlComp3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlComp3;

        /// <summary>
        /// imgM4 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgM4;

        /// <summary>
        /// hlComp4 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlComp4;
    }
}
