//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillSync.Pages.client
{


    public partial class MatchResults
    {

        /// <summary>
        /// lblSummaryCat control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSummaryCat;

        /// <summary>
        /// lblSummarySkills control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSummarySkills;

        /// <summary>
        /// lblSummaryBudget control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSummaryBudget;

        /// <summary>
        /// lblSummaryExp control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSummaryExp;

        /// <summary>
        /// lblSummaryLoc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSummaryLoc;

        /// <summary>
        /// hlEditReq control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlEditReq;

        /// <summary>
        /// ddlFiltCat control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltCat;

        /// <summary>
        /// ddlFiltBudget control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltBudget;

        /// <summary>
        /// ddlFiltExp control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltExp;

        /// <summary>
        /// ddlFiltMode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltMode;

        /// <summary>
        /// btnApplyFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnApplyFilter;

        /// <summary>
        /// ddlSelectFreelancerID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSelectFreelancerID;

        /// <summary>
        /// pnlHireSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlHireSuccess;

        /// <summary>
        /// lblHireMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblHireMsg;

        /// <summary>
        /// rptMatchResults control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptMatchResults;
    }
}
